### ISSUE TITLE
libraries version with requirements is needed

### ISSUE THREAD

**Issue by tabishqidwai98** [genieincodebottle/generative-ai#1]
The libraries have changed a lot, the last You updated the notebook. Can you please include the requirements file with versions in it? I was trying to work on this hello_genai.py file. 

will you please include this file, requiremnents.txt

![Screenshot 2024-04-03 141146](https://github.com/genieincodebottle/generative-ai/assets/60247314/1d7cc3ee-f873-47fe-89e2-ef40a6064ae3)

if this the proper channel, or just tell me. how?

**Comment by genieincodebottle** [comment]
Hi Tabish- Sure I will provide that. I will be uploading new content from
scratch from April 3rd week so thought to provide latest details in new
videos.


Thanks

**Comment by tabishqidwai98** [comment]
Hi Rajesh.

Can you please add it here too, thank you.

ping me once when have added the file, add the requirements file, it is necessary

**Comment by genieincodebottle** [comment]
@tabishqidwai98  Sorry for very late reply. Stuck in some priority things. I updated library and related code and added requirements.txt in Day-1 code. I am checking all other days code one by one and will update in 1-2 days. Let me know if still issue
